local M = {}

local defaults = {
  jira = {
    url = "",
    user = "",
    token = "",
  },
  azdo = {
    url     = "",  -- e.g. "https://dev.azure.com/myorg"
    project = "",  -- Azure DevOps project name
    repo    = "",  -- Git repository name within the project
    token   = "",  -- Personal Access Token (or use AZDO_TOKEN env var)
  },
  filters = {
    {
      name = "My Issues",
      jql = "assignee = currentUser() AND status != Done ORDER BY updated DESC",
    },
  },
  keymaps = {
    open   = "<leader>jj",
    toggle = "<leader>jt",
  },
  bin_path = nil, -- explicit path to jira-anvil binary (optional)

  -- Terminal window options
  win = {
    position = "float",  -- "float" | "right" | "bottom"
    rounded  = false,    -- rounded border (floating windows only)
    -- width  = nil,     -- explicit width in columns  (optional)
    -- height = nil,     -- explicit height in rows    (optional)
  },
}

M.options = vim.deepcopy(defaults)

--- Setup merges user options into M.options and writes the config YAML.
---@param opts table
function M.setup(opts)
  M.options = vim.tbl_deep_extend("force", vim.deepcopy(defaults), opts or {})
  M.write_yaml()
end

--- write_yaml writes the current options to ~/.config/anvil/config.yaml.
function M.write_yaml()
  local cfg = M.options
  local lines = { "# Generated by anvil.nvim — do not edit manually", "jira:" }

  local function escape(s)
    s = tostring(s or "")
    -- Quote if contains special YAML characters
    if s:match('[:#{}%[%],&*?|>!%%@`\'"\\]') or s:match("^%s") or s:match("%s$") then
      return '"' .. s:gsub('"', '\\"') .. '"'
    end
    return s
  end

  -- Resolve token: prefer env var if configured value looks like an env var ref
  local token = cfg.jira.token or vim.env.JIRA_API_TOKEN or ""
  local user  = cfg.jira.user  or vim.env.JIRA_USER  or ""
  local url   = cfg.jira.url   or vim.env.JIRA_URL   or ""

  table.insert(lines, "  url: "   .. escape(url))
  table.insert(lines, "  user: "  .. escape(user))
  table.insert(lines, "  token: " .. escape(token))

  -- Azure DevOps section (optional)
  local azdo = cfg.azdo or {}
  local azdo_url     = azdo.url     or vim.env.AZDO_URL     or ""
  local azdo_project = azdo.project or vim.env.AZDO_PROJECT or ""
  local azdo_repo    = azdo.repo    or vim.env.AZDO_REPO    or ""
  local azdo_token   = azdo.token   or vim.env.AZDO_TOKEN   or ""
  table.insert(lines, "azdo:")
  table.insert(lines, "  url: "     .. escape(azdo_url))
  table.insert(lines, "  project: " .. escape(azdo_project))
  table.insert(lines, "  repo: "    .. escape(azdo_repo))
  table.insert(lines, "  token: "   .. escape(azdo_token))

  table.insert(lines, "filters:")

  for _, filter in ipairs(cfg.filters or {}) do
    table.insert(lines, "  - name: " .. escape(filter.name or ""))
    table.insert(lines, "    jql: "  .. escape(filter.jql  or ""))
  end

  local config_dir  = vim.fn.expand("~/.config/anvil")
  local config_path = config_dir .. "/config.yaml"

  -- Ensure directory exists
  vim.fn.mkdir(config_dir, "p")

  local ok, err = pcall(function()
    local f = io.open(config_path, "w")
    if not f then
      error("cannot open " .. config_path)
    end
    f:write(table.concat(lines, "\n") .. "\n")
    f:close()
  end)

  if not ok then
    vim.notify("anvil: failed to write config: " .. tostring(err), vim.log.levels.WARN)
  end
end

--- bin returns the path to the jira-anvil binary.
--- Checks: explicit bin_path → PATH → plugin bin/ directory.
---@return string|nil
function M.bin()
  local opts = M.options
  if opts.bin_path and vim.fn.executable(opts.bin_path) == 1 then
    return opts.bin_path
  end

  local on_path = vim.fn.exepath("jira-anvil")
  if on_path ~= "" then
    return on_path
  end

  -- Check plugin's own bin/ directory
  local plugin_bin = vim.fn.fnamemodify(
    debug.getinfo(1, "S").source:sub(2),
    ":h:h:h"
  ) .. "/bin/jira-anvil"

  if vim.fn.executable(plugin_bin) == 1 then
    return plugin_bin
  end

  return nil
end

return M
